"""empty message

Revision ID: 02de025ac184
Revises: b45df29f86e0
Create Date: 2020-05-05 13:56:53.311943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02de025ac184'
down_revision = 'b45df29f86e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_post', sa.Column('last_commenter', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum_post', 'last_commenter')
    # ### end Alembic commands ###
