"""empty message

Revision ID: 0ab7d750568d
Revises: 474743eb2679
Create Date: 2022-03-14 15:48:52.385180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ab7d750568d'
down_revision = '474743eb2679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist_list', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_list', sa.Column('content', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
