"""empty message

Revision ID: 14d35882c50e
Revises: dd2c6ddcd626
Create Date: 2022-05-01 08:24:20.343121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14d35882c50e'
down_revision = 'dd2c6ddcd626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_albums', sa.Column('album_type', sa.String(length=255), nullable=True))
    op.drop_column('work_albums', 'compilation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_albums', sa.Column('compilation', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('work_albums', 'album_type')
    # ### end Alembic commands ###
