"""empty message

Revision ID: 16c9b422eabd
Revises: 2221197c9a0c
Create Date: 2021-05-06 08:20:01.920627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c9b422eabd'
down_revision = '2221197c9a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_list', sa.Column('nickname', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_list', 'nickname')
    # ### end Alembic commands ###
