"""empty message

Revision ID: 18e871a50ddb
Revises: 0ab7d750568d
Create Date: 2022-03-14 15:49:15.242456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e871a50ddb'
down_revision = '0ab7d750568d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_list', sa.Column('content', sa.String(length=4294000000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist_list', 'content')
    # ### end Alembic commands ###
