"""empty message

Revision ID: 19d4e5d097dc
Revises: e753fcb52b89
Create Date: 2023-03-31 11:38:10.543800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d4e5d097dc'
down_revision = 'e753fcb52b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('got_artists', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_albums', schema=None) as batch_op:
        batch_op.drop_column('got_artists')

    # ### end Alembic commands ###
