"""empty message

Revision ID: 1d15359e93fb
Revises: 01fcba5d5489
Create Date: 2023-04-26 13:44:59.729391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d15359e93fb'
down_revision = '01fcba5d5489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performer_albums', schema=None) as batch_op:
        batch_op.drop_constraint('performer_albums_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'work_albums', ['album_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('work_albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('markets', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_work_albums_album_id'), ['album_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_albums_album_type'), ['album_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_albums_score'), ['score'], unique=False)

    with op.batch_alter_table('work_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_loaded', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_list', schema=None) as batch_op:
        batch_op.drop_column('spotify_loaded')

    with op.batch_alter_table('work_albums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_albums_score'))
        batch_op.drop_index(batch_op.f('ix_work_albums_album_type'))
        batch_op.drop_index(batch_op.f('ix_work_albums_album_id'))
        batch_op.drop_column('markets')

    with op.batch_alter_table('performer_albums', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('performer_albums_ibfk_1', 'work_albums', ['album_id'], ['id'])

    # ### end Alembic commands ###
