"""empty message

Revision ID: 2221197c9a0c
Revises: d951fca07509
Create Date: 2020-05-10 12:00:53.148428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2221197c9a0c'
down_revision = 'd951fca07509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_list', sa.Column('album_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_list', 'album_count')
    # ### end Alembic commands ###
