"""empty message

Revision ID: 26add4047d97
Revises: a6b210d075a5
Create Date: 2022-03-09 15:50:43.172929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26add4047d97'
down_revision = 'a6b210d075a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composer_cron',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('composer_cron')
    # ### end Alembic commands ###
