"""empty message

Revision ID: 2a17ce282348
Revises: 19d4e5d097dc
Create Date: 2023-03-31 13:13:30.211998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a17ce282348'
down_revision = '19d4e5d097dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performer_albums')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performer_albums',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('performer_id', mysql.VARCHAR(length=48), nullable=True),
    sa.Column('work_id', mysql.VARCHAR(length=24), nullable=True),
    sa.Column('album_id', mysql.VARCHAR(length=46), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['work_albums.id'], name='performer_albums_ibfk_1'),
    sa.ForeignKeyConstraint(['performer_id'], ['performers.id'], name='performer_albums_ibfk_2'),
    sa.ForeignKeyConstraint(['work_id'], ['work_list.id'], name='performer_albums_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
