"""empty message

Revision ID: 2da16cd278de
Revises: 16c9b422eabd
Create Date: 2021-05-10 19:54:22.008765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da16cd278de'
down_revision = '16c9b422eabd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_albums', sa.Column('hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_albums', 'hidden')
    # ### end Alembic commands ###
