"""empty message

Revision ID: 30e22bce36e9
Revises: a20a997e715e
Create Date: 2022-04-27 19:10:30.735477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e22bce36e9'
down_revision = 'a20a997e715e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_list', sa.Column('img', sa.String(length=1024), nullable=True))
    op.add_column('work_list', sa.Column('spotify_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_list', 'spotify_data')
    op.drop_column('work_list', 'img')
    # ### end Alembic commands ###
