"""empty message

Revision ID: 3ea17cd87963
Revises: bcd84901e288
Create Date: 2023-04-30 19:04:57.188638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ea17cd87963'
down_revision = 'bcd84901e288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_albums', schema=None) as batch_op:
        batch_op.drop_column('got_artists')
        batch_op.drop_column('spotify_data')
        batch_op.drop_column('filled')
        batch_op.drop_column('markets')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('markets', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('filled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('spotify_data', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('got_artists', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
