"""empty message

Revision ID: 448e7a374010
Revises: 52398a418c32
Create Date: 2022-12-07 09:41:41.104214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448e7a374010'
down_revision = '52398a418c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_work_list_cat'), 'work_list', ['cat'], unique=False)
    op.create_index(op.f('ix_work_list_composer'), 'work_list', ['composer'], unique=False)
    op.create_index(op.f('ix_work_list_genre'), 'work_list', ['genre'], unique=False)
    op.create_index(op.f('ix_work_list_order'), 'work_list', ['order'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_list_order'), table_name='work_list')
    op.drop_index(op.f('ix_work_list_genre'), table_name='work_list')
    op.drop_index(op.f('ix_work_list_composer'), table_name='work_list')
    op.drop_index(op.f('ix_work_list_cat'), table_name='work_list')
    # ### end Alembic commands ###
