"""empty message

Revision ID: 474743eb2679
Revises: 66bcc77447c9
Create Date: 2022-03-14 15:34:55.381063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474743eb2679'
down_revision = '66bcc77447c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_list', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_artist_list_timestamp'), 'artist_list', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artist_list_timestamp'), table_name='artist_list')
    op.drop_column('artist_list', 'timestamp')
    # ### end Alembic commands ###
