"""empty message

Revision ID: 4b5ed8d705ff
Revises: 538c64a8ce94
Create Date: 2023-04-27 16:22:54.230218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b5ed8d705ff'
down_revision = '538c64a8ce94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_list', schema=None) as batch_op:
        batch_op.drop_column('spotify_loaded')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_loaded', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
