"""empty message

Revision ID: 4c0fd6b48750
Revises: 
Create Date: 2020-04-21 09:38:18.074607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c0fd6b48750'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'artists', 'work_albums', ['album_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artists', type_='foreignkey')
    # ### end Alembic commands ###
