"""empty message

Revision ID: 52398a418c32
Revises: 93ed1f56d493
Create Date: 2022-12-06 17:50:37.729412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52398a418c32'
down_revision = '93ed1f56d493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_composer_list_born'), 'composer_list', ['born'], unique=False)
    op.create_index(op.f('ix_composer_list_died'), 'composer_list', ['died'], unique=False)
    op.create_index(op.f('ix_composer_list_name_norm'), 'composer_list', ['name_norm'], unique=False)
    op.create_index(op.f('ix_composer_list_name_short'), 'composer_list', ['name_short'], unique=True)
    op.create_index(op.f('ix_composer_list_region'), 'composer_list', ['region'], unique=False)
    op.drop_index('name_short', table_name='composer_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name_short', 'composer_list', ['name_short'], unique=True)
    op.drop_index(op.f('ix_composer_list_region'), table_name='composer_list')
    op.drop_index(op.f('ix_composer_list_name_short'), table_name='composer_list')
    op.drop_index(op.f('ix_composer_list_name_norm'), table_name='composer_list')
    op.drop_index(op.f('ix_composer_list_died'), table_name='composer_list')
    op.drop_index(op.f('ix_composer_list_born'), table_name='composer_list')
    # ### end Alembic commands ###
