"""empty message

Revision ID: 52d62c5c9694
Revises: 217e5204024d
Create Date: 2023-03-31 13:21:20.776200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d62c5c9694'
down_revision = '217e5204024d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performer_albums',
    sa.Column('performer_id', sa.String(length=48), nullable=True),
    sa.Column('album_id', sa.String(length=46), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['work_albums.id'], ),
    sa.ForeignKeyConstraint(['performer_id'], ['performers.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performer_albums')
    # ### end Alembic commands ###
