"""empty message

Revision ID: 538c64a8ce94
Revises: 6804471cc8cd
Create Date: 2023-04-27 14:44:35.931128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538c64a8ce94'
down_revision = '6804471cc8cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_refresh', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_list', schema=None) as batch_op:
        batch_op.drop_column('last_refresh')

    # ### end Alembic commands ###
