"""empty message

Revision ID: 5c489d2a83b2
Revises: bb3dffb58f9d
Create Date: 2021-05-11 16:38:59.675103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c489d2a83b2'
down_revision = 'bb3dffb58f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('page_viewing', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'page_viewing')
    # ### end Alembic commands ###
