"""empty message

Revision ID: 5d2e03d78c6e
Revises: f26e783b12a6
Create Date: 2020-05-05 13:46:04.640410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2e03d78c6e'
down_revision = 'f26e783b12a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_post', sa.Column('last_commenter', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'forum_post', 'user', ['last_commenter'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forum_post', type_='foreignkey')
    op.drop_column('forum_post', 'last_commenter')
    # ### end Alembic commands ###
