"""empty message

Revision ID: 5d5da7b75989
Revises: 3ea17cd87963
Create Date: 2023-04-30 19:58:46.791969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d5da7b75989'
down_revision = '3ea17cd87963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spotify')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spotify',
    sa.Column('id', mysql.VARCHAR(length=24), nullable=False),
    sa.Column('composer', mysql.VARCHAR(length=48), nullable=True),
    sa.Column('results', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('updated', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
