"""empty message

Revision ID: 64dd9af50d86
Revises: bf623dfbfe19
Create Date: 2023-03-30 18:44:35.993511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64dd9af50d86'
down_revision = 'bf623dfbfe19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_id', sa.String(length=48), nullable=True))
        batch_op.add_column(sa.Column('spotify_img', sa.String(length=128), nullable=True))

    with op.batch_alter_table('work_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_list_album_count'), ['album_count'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_list_album_count'))

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('spotify_img')
        batch_op.drop_column('spotify_id')

    # ### end Alembic commands ###
