"""empty message

Revision ID: 6804471cc8cd
Revises: 1d15359e93fb
Create Date: 2023-04-27 14:42:21.061382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6804471cc8cd'
down_revision = '1d15359e93fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_img', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('wiki_link', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performers', schema=None) as batch_op:
        batch_op.drop_column('wiki_link')
        batch_op.drop_column('google_img')

    # ### end Alembic commands ###
