"""empty message

Revision ID: 733cee36f1b3
Revises: f80e0d8db885
Create Date: 2021-05-18 08:34:27.854005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733cee36f1b3'
down_revision = 'f80e0d8db885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('patreon', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'patreon')
    # ### end Alembic commands ###
