"""empty message

Revision ID: 7bc1fc22cbdc
Revises: 95b119fd7a89
Create Date: 2020-04-22 11:14:18.676449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc1fc22cbdc'
down_revision = '95b119fd7a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('album_like_ibfk_1', 'album_like', type_='foreignkey')
    op.create_foreign_key(None, 'album_like', 'work_albums', ['album_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'album_like', type_='foreignkey')
    op.create_foreign_key('album_like_ibfk_1', 'album_like', 'work_albums', ['album_id'], ['id'])
    # ### end Alembic commands ###
