"""empty message

Revision ID: 80afb195daaf
Revises: e84bb35ade86
Create Date: 2020-05-04 09:17:33.511467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80afb195daaf'
down_revision = 'e84bb35ade86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('forum_comment_ibfk_1', 'forum_comment', type_='foreignkey')
    op.create_foreign_key(None, 'forum_comment', 'forum_post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forum_comment', type_='foreignkey')
    op.create_foreign_key('forum_comment_ibfk_1', 'forum_comment', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###
