"""empty message

Revision ID: 93ed1f56d493
Revises: d64c4bee7166
Create Date: 2022-12-06 17:23:43.956383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ed1f56d493'
down_revision = 'd64c4bee7166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_album_like_user_id'), 'album_like', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_album_like_user_id'), table_name='album_like')
    # ### end Alembic commands ###
