"""empty message

Revision ID: 95b119fd7a89
Revises: 13517812d1e3
Create Date: 2020-04-21 22:01:34.663237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b119fd7a89'
down_revision = '13517812d1e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_albums',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('artists', sa.Text(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('composer_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('name_short', sa.String(length=255), nullable=True),
    sa.Column('name_full', sa.String(length=255), nullable=True),
    sa.Column('name_norm', sa.String(length=255), nullable=True),
    sa.Column('born', sa.Integer(), nullable=True),
    sa.Column('died', sa.Integer(), nullable=True),
    sa.Column('linkname', sa.String(length=255), nullable=True),
    sa.Column('nationality', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('imgfull', sa.String(length=255), nullable=True),
    sa.Column('pageurl', sa.String(length=255), nullable=True),
    sa.Column('wordcount', sa.Integer(), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('rank', sa.Float(), nullable=True),
    sa.Column('spotify', sa.String(length=255), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('catalogued', sa.Boolean(), nullable=True),
    sa.Column('female', sa.Boolean(), nullable=True),
    sa.Column('general', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_short')
    )
    op.create_table('spotify',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('composer', sa.String(length=48), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('img', sa.String(length=1024), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('work_images',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('genre', sa.String(length=128), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_list',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('composer', sa.String(length=48), nullable=True),
    sa.Column('genre', sa.String(length=128), nullable=True),
    sa.Column('order', sa.Float(), nullable=True),
    sa.Column('cat', sa.String(length=24), nullable=True),
    sa.Column('recommend', sa.String(length=24), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('search', sa.String(length=256), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('workid', sa.String(length=24), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workid'], ['work_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    op.create_table('favorites',
    sa.Column('composer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['composer_id'], ['composer_list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('visits',
    sa.Column('work_id', sa.String(length=24), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work_list.id'], )
    )
    op.create_table('work_albums',
    sa.Column('id', sa.String(length=46), nullable=False),
    sa.Column('workid', sa.String(length=24), nullable=True),
    sa.Column('album_id', sa.String(length=22), nullable=True),
    sa.Column('composer', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('artists', sa.Text(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['composer'], ['composer_list.name_short'], ),
    sa.ForeignKeyConstraint(['workid'], ['work_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('album_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('album_id', sa.String(length=46), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['work_albums.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artists',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('workid', sa.String(length=24), nullable=True),
    sa.Column('album_id', sa.String(length=46), nullable=True),
    sa.Column('composer', sa.String(length=48), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['work_albums.id'], ),
    sa.ForeignKeyConstraint(['workid'], ['work_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artists')
    op.drop_table('album_like')
    op.drop_table('work_albums')
    op.drop_table('visits')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('followers')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.drop_table('comment')
    op.drop_table('work_list')
    op.drop_table('work_images')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('spotify')
    op.drop_table('composer_list')
    op.drop_table('artist_albums')
    # ### end Alembic commands ###
