"""empty message

Revision ID: a20a997e715e
Revises: 18e871a50ddb
Create Date: 2022-03-14 15:50:53.608748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20a997e715e'
down_revision = '18e871a50ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_list', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist_list', 'content')
    # ### end Alembic commands ###
