"""empty message

Revision ID: a6b210d075a5
Revises: 733cee36f1b3
Create Date: 2021-05-25 11:33:23.111177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b210d075a5'
down_revision = '733cee36f1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('composer_list', sa.Column('preview_music', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('composer_list', 'preview_music')
    # ### end Alembic commands ###
