"""empty message

Revision ID: bb3dffb58f9d
Revises: 576b9db05a88
Create Date: 2021-05-11 16:23:33.778932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3dffb58f9d'
down_revision = '576b9db05a88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'album_like', 'work_albums', ['album_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'album_like', type_='foreignkey')
    # ### end Alembic commands ###
