"""empty message

Revision ID: bcd84901e288
Revises: 4b5ed8d705ff
Create Date: 2023-04-30 16:52:38.271701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd84901e288'
down_revision = '4b5ed8d705ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_list', schema=None) as batch_op:
        batch_op.drop_index('ix_work_list_composer')
        batch_op.create_foreign_key(None, 'composer_list', ['composer'], ['name_short'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_work_list_composer', ['composer'], unique=False)

    # ### end Alembic commands ###
