"""empty message

Revision ID: beb83071ed39
Revises: 14d35882c50e
Create Date: 2022-05-04 14:15:52.015170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb83071ed39'
down_revision = '14d35882c50e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_albums', sa.Column('work_track_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_albums', 'work_track_count')
    # ### end Alembic commands ###
