"""empty message

Revision ID: c7f4c3524259
Revises: 30e22bce36e9
Create Date: 2022-04-27 19:12:45.957279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7f4c3524259'
down_revision = '30e22bce36e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_albums', sa.Column('img', sa.Text(), nullable=True))
    op.add_column('work_albums', sa.Column('spotify_data', sa.Text(), nullable=True))
    op.drop_column('work_list', 'img')
    op.drop_column('work_list', 'spotify_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_list', sa.Column('spotify_data', mysql.TEXT(), nullable=True))
    op.add_column('work_list', sa.Column('img', mysql.VARCHAR(length=1024), nullable=True))
    op.drop_column('work_albums', 'spotify_data')
    op.drop_column('work_albums', 'img')
    # ### end Alembic commands ###
