"""empty message

Revision ID: cdcb7f3403e8
Revises: beb83071ed39
Create Date: 2022-05-18 09:07:38.145842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdcb7f3403e8'
down_revision = 'beb83071ed39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('country', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('product', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'product')
    op.drop_column('user', 'country')
    # ### end Alembic commands ###
