"""empty message

Revision ID: dd2c6ddcd626
Revises: a23b173bf46e
Create Date: 2022-05-01 08:21:47.881172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2c6ddcd626'
down_revision = 'a23b173bf46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_albums', sa.Column('track_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_albums', 'track_count')
    # ### end Alembic commands ###
