"""empty message

Revision ID: e4af47fc5d17
Revises: 188f2980f614
Create Date: 2022-12-29 17:07:06.417176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4af47fc5d17'
down_revision = '188f2980f614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy_table',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dummy_table')
    # ### end Alembic commands ###
