"""empty message

Revision ID: e72ebb739321
Revises: 4fda3b1fdd76
Create Date: 2020-04-21 09:46:18.874139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72ebb739321'
down_revision = '4fda3b1fdd76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('workid', sa.VARCHAR(length=24), nullable=True),
    sa.Column('composer', sa.VARCHAR(length=48), nullable=True),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.Column('album_id', sa.VARCHAR(length=46), nullable=True),
    sa.ForeignKeyConstraint(['workid'], ['work_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
