"""empty message

Revision ID: f26e783b12a6
Revises: 80afb195daaf
Create Date: 2020-05-05 13:26:07.482886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26e783b12a6'
down_revision = '80afb195daaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_post', sa.Column('last_comment_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum_post', 'last_comment_date')
    # ### end Alembic commands ###
