"""empty message

Revision ID: f74b05e83ab7
Revises: e418dc269b45
Create Date: 2023-04-04 10:49:30.015654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74b05e83ab7'
down_revision = 'e418dc269b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_albums', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
