"""empty message

Revision ID: f80e0d8db885
Revises: 49b4ac4076b6
Create Date: 2021-05-13 18:37:36.938899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80e0d8db885'
down_revision = '49b4ac4076b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_albums', sa.Column('filled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_albums', 'filled')
    # ### end Alembic commands ###
