"""empty message

Revision ID: ff7519450ddb
Revises: 57c8a27b56c4
Create Date: 2020-05-05 14:10:50.356375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff7519450ddb'
down_revision = '57c8a27b56c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_post', sa.Column('last_comment_username', sa.String(length=64), nullable=True))
    op.drop_column('forum_post', 'last_comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_post', sa.Column('last_comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('forum_post', 'last_comment_username')
    # ### end Alembic commands ###
